[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

remappings = [
    "@ensdomains=node_modules/@ensdomains/",
    "@unruggable=lib/unruggable-gateways/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
