name: Unruggable Gateways Resolution Demo
on: [push]
jobs:
  test:
    name: Run examples using Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['20.x']
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Bun 1.1.26
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.26

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
  
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.3.1

      - name: 'Create env file'
        run: |
          touch .env
          echo ALCHEMY_KEY=${{ secrets.ALCHEMY_KEY }} >> .env
          echo INFURA_KEY=${{ secrets.INFURA_KEY }} >> .env
          echo DRPC_KEY=${{ secrets.DRPC_KEY }} >> .env
          echo IS_CI=true >> .env
          cat .env

      - name: Install Dependencies
        run: bun install

      - name: Run Optimism Example
        run: bun run optimism.ts

      - name: Run Base Example
        run: bun run base.ts

      - name: Run Arbitrum Example
        run: bun run arbitrum.ts